<?php

namespace portalium\menu\components;

use portalium\menu\models\Menu;
use Yii;

use yii\base\BaseObject;


class TriggerActions extends BaseObject
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}